name: nmea_to_network
description: An app that sends NMEA sentences over a network.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.8
  udp: ^5.0.3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  map: 1.0.1
  cached_network_image: ^3.3.1
  network_info_plus: ^6.0.0
  toast: ^0.3.0
  flutter_compass: ^0.7.0
  lan_scanner: ^3.5.0
  shared_preferences: ^2.2.2
  latlng: ^2.0.0
  ffi: ^2.1.0
  usb_serial: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
